import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css';
import ReactIntlProvider from "@/src/providers/intl-provider";
import Header from "@/src/components/organisms/Header";
import AntdStyledComponentsRegistry from "../lib/AntdStyledComponentsRegistry"; 
import ReactQueryProvider from "@/src/providers/query-provider";
import { NotificationProvider } from "../providers/notificationProvider";
import { ProviderWrapper } from "../lib/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = 'en';

  return (
    <html lang="en">
      <ReactQueryProvider>
        <ReactIntlProvider locale={locale}>
          <AntdStyledComponentsRegistry>
             <NotificationProvider>
              <ProviderWrapper>
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-100`}
            >
              <Header />
              {children}
            </body>
            </ProviderWrapper>
            </NotificationProvider>
            
          </AntdStyledComponentsRegistry>
        </ReactIntlProvider>
      </ReactQueryProvider>
    </html>
  );
}
