
org: management1

service: expenses-service

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  stage: ${opt:stage,'dev'}
  environment:

custom:
  serverless-offline:
     httpPort: 3004
     lambdaPort: 3005

plugins:
  - serverless-offline
  - serverless-dotenv-plugin


functions:
  handler:
    handler: handler.handler
    timeout: 10
    events:
      - http: 
          path: expenses
          method: get
          cors: true
      - http: 
          path: expenses/{id}
          method: get
          cors: true
      - http: 
          path: /expenses/create
          method: post
          cors: true
      - http: 
          path: /expenses/update
          method: put
          cors: true
      - http: 
          path: expenses/{id}
          method: delete
          cors: true
  

# functions:
#   getExpenses:
#     handler: handlers/index.getExpenses
#     events:
#       - http: 
#           path: expenses
#           method: get
#           cors: true

  # handler:
  #   handler: handler.handler
  #   events:
  #     - httpApi: 
  #         path: ha
  #         method: get
  #         cors: true

  # addExpenses:
  #   handler: handlers/index.addExpenses
  #   events:
  #     - http: 
  #         path: expenses
  #         method: post
  #         cors: true
