
org: management1

service: expenses-service

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  stage: ${opt:stage,'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"
  environment:
    MONGODB_URI: ${ssm:/mongo_url}
    ACCESS_TOKEN_SECRET: ${ssm:/access_token}
    REFRESH_TOKEN_SECRET: ${ssm:/refresh_token}

custom:
  serverless-offline:
     httpPort: 3004
     lambdaPort: 3005

plugins:
  - serverless-offline
  - serverless-dotenv-plugin


functions:
  handler:
    handler: handler.handler
    timeout: 10
    events:
      - http: 
          path: expenses
          method: get
          cors:
            origin: http://frontendhost1.s3-website.ap-south-1.amazonaws.com
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
      - http: 
          path: expenses/{id}
          method: get
          cors:
            origin: http://frontendhost1.s3-website.ap-south-1.amazonaws.com
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
      - http: 
          path: /expenses/create
          method: post
          cors:
            origin: http://frontendhost1.s3-website.ap-south-1.amazonaws.com
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
      - http: 
          path: /expenses/update
          method: put
          cors:
            origin: http://frontendhost1.s3-website.ap-south-1.amazonaws.com
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
      - http: 
          path: expenses/{id}
          method: delete
          cors:
            origin: http://frontendhost1.s3-website.ap-south-1.amazonaws.com
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
          
      - http: 
          path: /expenses/limit/{id}
          method: get
          cors:
            origin: http://frontendhost1.s3-website.ap-south-1.amazonaws.com
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
  

# functions:
#   getExpenses:
#     handler: handlers/index.getExpenses
#     events:
#       - http: 
#           path: expenses
#           method: get
#           cors: true

  # handler:
  #   handler: handler.handler
  #   events:
  #     - httpApi: 
  #         path: ha
  #         method: get
  #         cors: true

  # addExpenses:
  #   handler: handlers/index.addExpenses
  #   events:
  #     - http: 
  #         path: expenses
  #         method: post
  #         cors: true
