service: auth-service

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"
  environment:
    MONGODB_URI: ${ssm:/mongo_url}
    ACCESS_TOKEN_SECRET: ${ssm:/access_token}
    REFRESH_TOKEN_SECRET: ${ssm:/refresh_token}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 3002
    lambdaPort: 3006

functions:
  api:
    handler: handler.handler
    timeout: 15
    events:
      - http:
          path: /{proxy+}
          method: any
          cors:
            origin: http://frontendhost1.s3-website.ap-south-1.amazonaws.com
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
